# Generated by Django 2.1.7 on 2019-03-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10, verbose_name='名字')),
                ('last_name', models.CharField(max_length=10, verbose_name='姓')),
                ('age', models.PositiveIntegerField(verbose_name='年齡')),
                ('politics', models.TextField(verbose_name='政見')),
                ('vote', models.PositiveIntegerField(verbose_name='得票數')),
            ],
        ),
    ]
